let words: string[] = [
  'COMPUTADORA','AGUACATE','TECLADO','PANTALLA','MONITOR','IMPRESORA','RATON','LAPTOP','TABLET','CELULAR',
  'AURICULARES','CABLE','ROUTER','MODEM','CAMARA','MICROFONO','ALTAVOZ','BATERIA','CARGADOR','DRON',

  'TIGRE','LEON','JIRAFA','ELEFANTE','RINOCERONTE','HIPOPOTAMO','COCODRILO','DELFIN','TIBURON','BALLENA',
  'PINGUINO','PANTERA','LOBO','ZORRO','OSO','KOALA','CANGURO','ORNITORRINCO','BUFALO','AGUILA',
  'HALCON','LECHUZA','SERPIENTE','LAGARTO','TARANTULA',

  'MANZANA','PERA','NARANJA','PLATANO','FRESA','MANGO','SANDIA','PAPAYA','ARANDANO','COCO','LIMON',
  'TOMATE','CEBOLLA','ZANAHORIA','LECHUGA','CHOCOLATE','QUESO','TORTILLA','TACO','MOLE','POZOLE',
  'ENSALADA','SOPA','PAN','CAFE','TE',

  'ESCUELA','UNIVERSIDAD','HOSPITAL','AEROPUERTO','ESTADIO','MUSEO','BIBLIOTECA','TEATRO','PLAYA','MONTANA',
  'BOSQUE','DESIERTO','VOLCAN','CIUDAD','PUEBLO','MERCADO',

  'CORRER','NADAR','SALTAR','CAMINAR','ESCRIBIR','LEER','DIBUJAR','CANTAR','BAILAR','VIAJAR','PENSAR',
  'ESTUDIAR','PROGRAMAR','DEPURAR','COMPILAR','DISENAR','ENSAMBLAR','SOLDAR','PROBAR','MEDIR','CALCULAR',

  'ALGORITMO','PROGRAMA','VARIABLE','FUNCION','CLASE','OBJETO','ARREGLO','VECTOR','MATRIZ','CIRCUITO',
  'RESISTENCIA','CAPACITOR','INDUCTOR','TRANSISTOR','DIODO','OSCILADOR','MICROCONTROLADOR','COMPILADOR',
  'LENGUAJE','INTERFAZ','SENSOR','ACTUADOR','ROBOTICA','ELECTRONICA','MECANICA','POTENCIA','FRECUENCIA',
  'AMPLITUD','IMPEDANCIA','PROTOCOLO','PUERTO','SERIE','PARALELO','ANALOGICO','DIGITAL','OSCILOSCOPIO',
  'MULTIMETRO','PROTOBOARD','SOLDADURA','FIRMWARE','HARDWARE','SOFTWARE',

  'UART','I2C','SPI','PWM',

  'ASTRONAUTA','SATELITE','COHETE','ORBITA','GALAXIA','ESTRELLA','PLANETA','NEBULOSA','GRAVEDAD','INERCIA',

  'TORMENTA','LLUVIA','RAYO','TRUENO','RELAMPAGO','NUBE','NIEVE','HIELO','VIENTO',

  'ROJO','AZUL','VERDE','AMARILLO','MORADO','NEGRO','BLANCO','GRIS','MAGENTA','CIAN',

  'MEXICO','ESPANA','ARGENTINA','COLOMBIA','PERU','CHILE','URUGUAY','PARAGUAY','ECUADOR','BOLIVIA',
  'GUATEMALA','HONDURAS','NICARAGUA','PANAMA','CANADA','FRANCIA','ITALIA','ALEMANIA','JAPON','CHINA','INDIA',

  'ALEGRIA','TRISTEZA','AMISTAD','FAMILIA','MUSICA','PELICULA','DEPORTE','JUEGO','AHORCADO',

  'MARTILLO','DESTORNILLADOR','ALICATES','TALADRO','SIERRA','LLAVE','TORNILLO','TUERCA','ARANDELA',

  'DERIVADA','INTEGRAL','ESCALAR','ANGULO','GRADO','RADIAN',

  'AUTOMOVIL','BICICLETA','MOTOCICLETA','CAMIONETA','CAMION','BARCO','AVION','TREN','METRO',

  'CALENDARIO','RELOJ','MINUTO','SEGUNDO','HORA'
];


export function getRandomWord() {

    const randomIndex = Math.floor( Math.random() * words.length );
    return words[randomIndex];
    
}